// <auto-generated />
namespace GigNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedmessagetrackandvideotables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedmessagetrackandvideotables));
        
        string IMigrationMetadata.Id
        {
            get { return "201607271633167_removed message, track, and video tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
