// <auto-generated />
namespace GigNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class turnFKintovirtualobjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(turnFKintovirtualobjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201607072259459_turn FK into virtual objects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
