// <auto-generated />
namespace GigNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedxtralinkpropfromartistmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedxtralinkpropfromartistmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201607092146130_removed xtra link prop from artist model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
