// <auto-generated />
namespace GigNow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedmessageandtypetonotif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmessageandtypetonotif));
        
        string IMigrationMetadata.Id
        {
            get { return "201607081740305_added message and type to notif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
